# Generated by Django 2.1.4 on 2019-04-26 18:26

from django.db import migrations, models
import places.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('presentation', models.ImageField(upload_to=places.models.upload_image_of_place)),
                ('rating', models.DecimalField(decimal_places=1, default=0.0, max_digits=1)),
                ('added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
