# Generated by Django 2.1.4 on 2019-05-11 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_place_posts'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='place',
            options={'verbose_name': 'Lugar', 'verbose_name_plural': 'Lugares'},
        ),
    ]
