# Generated by Django 2.1.4 on 2019-04-26 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatBot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('replyRegex', models.CharField(max_length=150, primary_key=True, serialize=False, verbose_name='Expresion regular de la respuesta')),
                ('replyText', models.CharField(max_length=150, verbose_name='Texto de la respuesta')),
            ],
        ),
        migrations.CreateModel(
            name='WordsRegex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wRegex', models.CharField(max_length=100, verbose_name='Regex Palabra')),
                ('wordsType', models.CharField(choices=[('S', 'sujeto'), ('V', 'verbo'), ('PI', 'pronombre Interrogativo')], max_length=2)),
            ],
        ),
    ]
