# Generated by Django 2.1.4 on 2019-05-06 00:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20190505_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='categorie',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='products.Categorie'),
        ),
    ]
