# Generated by Django 2.1.4 on 2019-05-11 22:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20190511_1826'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='operation',
        ),
        migrations.AddField(
            model_name='operationbuy',
            name='order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='products.order', verbose_name='Orden de compra'),
            preserve_default=False,
        ),
    ]
