# Generated by Django 2.1.4 on 2019-05-11 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20190511_1838'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorie',
            options={'verbose_name': 'Categoria', 'verbose_name_plural': 'Categorias'},
        ),
        migrations.AlterModelOptions(
            name='operationbuy',
            options={'verbose_name': 'Operacion de venta', 'verbose_name_plural': 'Lugares'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Orden de compra', 'verbose_name_plural': 'Ordenes de compra'},
        ),
        migrations.AlterModelOptions(
            name='productmodel',
            options={'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
    ]
